# Copyright 2025 Open Source Robotics Foundation, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cmake_minimum_required(VERSION 3.12)

project(ament_cmake_python_test)

find_package(ament_cmake_core REQUIRED)

# Uncomment to debug CMake variables
#
# get_cmake_property(_variableNames VARIABLES)
# list (SORT _variableNames)
# foreach (_variableName ${_variableNames})
#     message(STATUS "${_variableName}=${${_variableName}}")
# endforeach()

if(BUILD_TESTING)
  find_package(ament_lint_auto REQUIRED)
  ament_lint_auto_find_test_dependencies()

  find_package(ament_cmake_pytest REQUIRED)
  find_package(ament_cmake_python REQUIRED)
  find_package(ament_cmake REQUIRED)
  ament_get_python_install_dir(PYTHON_INSTALL_DIR)

  set(_pytest_tests
    test/test_packages.py
    # Add other test files here
  )

  set(_env SOURCE_DIR=${CMAKE_CURRENT_SOURCE_DIR})
  list(APPEND _env PYTHON_INSTALL_DIR=${PYTHON_INSTALL_DIR})
  list(APPEND _env PYEGG_VERSION=py${Python3_VERSION_MAJOR}.${Python3_VERSION_MINOR})
  foreach(_test_path ${_pytest_tests})
    get_filename_component(_test_name ${_test_path} NAME_WE)
    ament_add_pytest_test(${_test_name} ${_test_path}
      APPEND_ENV PYTHONPATH=${CMAKE_CURRENT_BINARY_DIR}
      ENV ${_env}
      TIMEOUT 360
      WORKING_DIRECTORY ${PROJECT_BINARY_DIR}
    )
  endforeach()

  find_package(ament_lint_auto REQUIRED)
  # the following line skips the linter which checks for copyrights
  # comment the line when a copyright and license is added to all source files
  set(ament_cmake_copyright_FOUND TRUE)
  # the following line skips cpplint (only works in a git repo)
  # comment the line when this package is in a git repo and when
  # a copyright and license is added to all source files
  set(ament_cmake_cpplint_FOUND TRUE)
  ament_lint_auto_find_test_dependencies()

endif()
ament_package()
