// Test the presense of the following header file
#include <ament_cmake_gen_version_h/version_custom.h>
#include <gtest/gtest.h>

TEST(test_ament_cmake_gen_version_h, version_custom)
{
  EXPECT_TRUE(AMENT_CMAKE_GEN_VERSION_H_VERSION_GTE(0, 0, 0));
  EXPECT_TRUE(AMENT_CMAKE_GEN_VERSION_H_VERSION_GTE(0, 1, 2));
  EXPECT_TRUE(AMENT_CMAKE_GEN_VERSION_H_VERSION_GTE(1, 2, 3));
  EXPECT_FALSE(AMENT_CMAKE_GEN_VERSION_H_VERSION_GTE(1, 2, 4));
  EXPECT_FALSE(AMENT_CMAKE_GEN_VERSION_H_VERSION_GTE(1, 3, 2));
  EXPECT_FALSE(AMENT_CMAKE_GEN_VERSION_H_VERSION_GTE(2, 1, 2));
  EXPECT_EQ(AMENT_CMAKE_GEN_VERSION_H_VERSION_MAJOR, 1);
  EXPECT_EQ(AMENT_CMAKE_GEN_VERSION_H_VERSION_MINOR, 2);
  EXPECT_EQ(AMENT_CMAKE_GEN_VERSION_H_VERSION_PATCH, 3);
  EXPECT_STREQ(AMENT_CMAKE_GEN_VERSION_H_VERSION_STR, "1.2.3");
}
